name: Sync Fork and Redeploy

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' 

jobs:
  check-if-fork:
    runs-on: ubuntu-latest
    outputs:
      is_fork: ${{ steps.check.outputs.is_fork }}
    steps:
      - id: check
        run: |
          if [ "${{ github.repository_owner }}" != "dreamhartley" ]; then
            echo "is_fork=true" >> $GITHUB_OUTPUT
          else
            echo "is_fork=false" >> $GITHUB_OUTPUT
          fi

  sync-and-deploy:
    needs: check-if-fork
    if: needs.check-if-fork.outputs.is_fork == 'true'
    runs-on: ubuntu-latest
    name: Sync fork with upstream and redeploy
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      
      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/dreamhartley/gemini-proxy-panel.git
          git fetch upstream
      
      - name: Sync fork with upstream
        run: |
          git checkout main
          git merge upstream/main
          git push origin main
